import {
  ArrowRight,
  BarChart3,
  BellRing,
  BriefcaseBusiness,
  Building2,
  Check,
  CheckCircle2,
  ChevronDown,
  Clock3,
  Code2,
  FileText,
  LayoutDashboard,
  LayoutTemplate,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MousePointerClick,
  Phone,
  RefreshCw,
  Rocket,
  Search,
  Send,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Target,
  UserRound,
  Workflow,
  Wrench,
  X,
} from "lucide-react";

const icons = {
  ArrowRight,
  BarChart3,
  BellRing,
  BriefcaseBusiness,
  Building2,
  Check,
  CheckCircle2,
  ChevronDown,
  Clock3,
  Code2,
  FileText,
  LayoutDashboard,
  LayoutTemplate,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MousePointerClick,
  Phone,
  RefreshCw,
  Rocket,
  Search,
  Send,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Target,
  UserRound,
  Workflow,
  Wrench,
  X,
};

export default function Icon({ name, className = "h-5 w-5", strokeWidth = 2 }) {
  const LucideIcon = icons[name] || Sparkles;
  return <LucideIcon className={className} strokeWidth={strokeWidth} />;
}
